name: shell commands

on:
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Multiline string
        run: |
          pwd
          node -v
          ls -a
  