name: shell commands

on:
  - push
jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform initialization
        run: terraform init
      - name: Terraform validation
        run: terraform validate