name: shell commands

on:
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terrafom
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.8
      -name: Terraform Initialization
        run: terraform init
      -name: Terraform validate
        run: terraform validate